/**
 * String table — every user-facing string flows through here (TECH §10, user decision
 * 2026-07-11: English-first, i18n-ready). Never hardcode UI text in components.
 * Adding a language later = adding a table, not a refactor.
 */

const en = {
  'app.title': 'Poplands',
  'app.tagline': 'Grow a cozy island in the sky, one pop at a time.',
  'loading.label': 'Un-fogging the sky…',
  'loading.hint': 'Drag to orbit · Scroll to zoom · WASD to pan',
  'error.webgl': 'Poplands needs WebGL2 — this browser or device doesn’t seem to support it.',
  'error.boot': 'Something went wrong while waking the island. Please refresh to try again.',
  'debug.title': 'Debug',

  // build UI
  'build.tab.all': 'All',
  'build.tab.nature': 'Nature',
  'build.tab.decor': 'Decor',
  'build.tab.home': 'Homes',
  'build.tab.income': 'Income',
  'build.tab.ground': 'Ground',
  'build.tool.move': 'Move',
  'build.tool.remove': 'Remove',
  'build.hint.place': 'Click to place · R rotates · Esc done',
  'build.hint.move': 'Click something to pick it up',
  'build.hint.carrying': 'Click to drop · R rotates · Esc puts it back',
  'build.hint.remove': 'Click something to remove it',
  'build.blocked.occupied': 'Something is already there',
  'build.blocked.island': 'That’s open sky!',
  'build.blocked.afford': 'Not enough Pops yet',
  'build.blocked.edge': 'Needs to reach the island’s edge',
  'build.locked': 'Unlocks at Level {level}',
  'toast.levelUp': 'Level {level}! ✨ New things to build',
  'toast.questDone': 'Postcard complete! 💌',
  'toast.secretFound': 'A discovery! ✨',
  'toast.npcArrived': '{name} moved in! 🏡',
  'toast.palAdopted': 'A {pal} came to visit! 🐾',

  // expansion (S8) — survey markers on the island's free edges
  'survey.call': 'Call this chunk',
  'chunk.popup.title': 'New chunk!',
  'chunk.popup.sub': 'Chunk {n} floated up to join your island 🌱',

  // islander chatter (S16) — cute one-liners shown in a speech bubble on tap
  'npc.say.1': 'Best little island in the sky!',
  'npc.say.2': 'Is that cloud shaped like a bun? 🥐',
  'npc.say.3': 'I could nap here forever…',
  'npc.say.4': 'Ooh, what are you building next?',
  'npc.say.5': 'The flowers smell amazing today.',
  'npc.say.6': 'Morning stroll = the best stroll.',
  'npc.say.7': 'Did you hear? A new chunk floated up!',
  'npc.say.8': 'I found a shiny pebble. It’s my favorite now.',
  'npc.say.9': 'Wave hello to the Pals for me! 🐾',
  'npc.say.10': 'So cozy up here. Thank you.',
  'npc.say.11': 'Wanna watch the stars later?',
  'npc.say.12': 'I’m just vibing, honestly.',
  'npc.say.13': 'You’re doing a wonderful job. ✨',
  'npc.say.14': 'Careful near the edge — big drop! 😅',

  // pals (S18) — species names, lower-case for "A {pal} came to visit!"
  'pal.cat.name': 'cat',
  'pal.dog.name': 'dog',
  'pal.bunny.name': 'bunny',
  'pal.chick.name': 'chick',
  'pal.pig.name': 'pig',
  'pal.cow.name': 'cow',

  // islanders (S16) — proper names; localized tables may transliterate
  'npc.mo.name': 'Mo',
  'npc.pia.name': 'Pia',
  'npc.bram.name': 'Bram',
  'npc.lulu.name': 'Lulu',
  'npc.fen.name': 'Fen',
  'npc.nix.name': 'Nix',
  'npc.oda.name': 'Oda',
  'npc.juno.name': 'Juno',
  'npc.taro.name': 'Taro',
  'npc.wren.name': 'Wren',
  'npc.sol.name': 'Sol',
  'npc.mika.name': 'Mika',
  'npc.posy.name': 'Posy',
  'npc.gus.name': 'Gus',
  'npc.ivy.name': 'Ivy',
  'npc.remy.name': 'Remy',

  // mailbox
  'mailbox.title': 'Postcards',
  'mailbox.empty': 'No postcards right now — just enjoy your island.',
  'mailbox.skip': 'Later',
  'mailbox.reward': 'Reward:',
  'hud.tutorialStep': 'Step {n}',

  // — tutorial "Welcome to the Drift"
  'quest.tut.flowers.t': 'A splash of color',
  'quest.tut.flowers.d': 'Open the catalog and plant 3 wildflowers anywhere.',
  'quest.tut.path.t': 'Find your footing',
  'quest.tut.path.d': 'Lay 3 path tiles to start a little walkway.',
  'quest.tut.bench.t': 'A place to sit',
  'quest.tut.bench.d': 'Set down a Garden Bench.',
  'quest.tut.stall.t': 'Your first earnings',
  'quest.tut.stall.d': 'Build a Flower Stall — it makes Pops over time.',
  'quest.tut.collect.t': 'Ripe and ready',
  'quest.tut.collect.d': 'Wait for the stall to ripen, then click it to collect Pops.',
  'quest.tut.hut.t': 'Somewhere to call home',
  'quest.tut.hut.d': 'Build a Cozy Hut. (Islanders move in a little later!)',
  'quest.tut.cozycorner.t': 'Cozy corner',
  'quest.tut.cozycorner.d': 'Place a Lantern within 2 tiles of your Hut.',
  'quest.tut.lanterns.t': 'Light the way',
  'quest.tut.lanterns.d': 'Place 2 Lanterns around your island.',
  'quest.tut.level2.t': 'Rising star',
  'quest.tut.level2.d': 'Reach Level 2. You’ll earn Stardust ✦ — the rare currency.',
  'quest.tut.pops150.t': 'Tidy sum',
  'quest.tut.pops150.d': 'Collect 150 Pops in total.',
  'quest.tut.level3.t': 'Growing up',
  'quest.tut.level3.d': 'Reach Level 3. The Drift will grow once you’re ready — for now, keep leveling.',
  'quest.tut.capstone.t': 'A little world of your own',
  'quest.tut.capstone.d': 'Fill your island — have 30 things placed. The Drift is waking up!',
  'quest.tut.callchunk.t': 'Call more land',
  'quest.tut.callchunk.d': 'Tap a floating Survey marker to call a new chunk up from the cloud sea.',
  'quest.tut.secret.t': 'Investigate the sparkle',
  'quest.tut.secret.d': 'Something glimmers on your island — click a ✨ and dig up its secret.',

  // — postcards
  'quest.pc.grove.t': 'Little grove',
  'quest.pc.grove.d': 'Plant 5 trees.',
  'quest.pc.paved.t': 'Winding ways',
  'quest.pc.paved.d': 'Lay 8 path tiles.',
  'quest.pc.blooming.t': 'In full bloom',
  'quest.pc.blooming.d': 'Place 10 nature items.',
  'quest.pc.cozycorner.t': 'Reading nook',
  'quest.pc.cozycorner.d': 'Put a Lantern within 2 tiles of a Garden Bench.',
  'quest.pc.firstearnings.t': 'Pocket money',
  'quest.pc.firstearnings.d': 'Collect 200 Pops.',
  'quest.pc.homeward.t': 'Homeward',
  'quest.pc.homeward.d': 'Have 2 homes on your island.',
  'quest.pc.greenthumb.t': 'Green thumb',
  'quest.pc.greenthumb.d': 'Own 20 nature items.',
  'quest.pc.farmlife.t': 'Farm life',
  'quest.pc.farmlife.d': 'Build a Pumpkin Patch or a Wheat Field.',
  'quest.pc.tidysum.t': 'Nest egg',
  'quest.pc.tidysum.d': 'Collect 500 Pops.',
  'quest.pc.village.t': 'A proper village',
  'quest.pc.village.d': 'Have 3 homes and 3 income buildings.',
  'quest.pc.treasure.t': 'X marks the spot',
  'quest.pc.treasure.d': 'Uncover a secret hidden on one of your chunks.',

  // — milestones (Album labels, surfaced in v0.6)
  'quest.ms.placed': 'Things placed',
  'quest.ms.pops': 'Pops collected',
  'quest.ms.quests': 'Postcards completed',

  // island album (S21, v0.6)
  'album.title': 'Island Album',
  'album.milestones': 'Milestones',
  'album.neighbours': 'Neighbours',
  'album.pals': 'Pals',
  'album.biomes': 'Biomes',
  'album.empty': 'Nobody yet — build a home!',

  // photo mode (S23, v0.6)
  'photo.hint': 'Photo Mode — drag to frame your island',
  'photo.save': 'Save PNG',
  'photo.exit': 'Exit',
  'photo.saved': 'Saved a snapshot! 📸',
  'photo.failed': 'Couldn’t save the photo.',

  // settings
  'settings.title': 'Settings',
  'settings.quality': 'Quality',
  'settings.quality.auto': 'Auto',
  'settings.quality.high': 'High',
  'settings.quality.medium': 'Medium',
  'settings.quality.low': 'Low',
  'settings.volume': 'Sound',
  'settings.time': 'Time of day',
  'settings.time.auto': 'Cycle',
  'settings.time.day': 'Day',
  'settings.time.dusk': 'Dusk',
  'settings.time.night': 'Night',
  'settings.reducedMotion': 'Reduce motion',
  'settings.fps': 'Frame cap',
  'settings.fps.off': 'Off',
  'settings.fps.30': '30 fps',
  'settings.fps.60': '60 fps',
  'settings.uiScale': 'UI size',
  'settings.uiScale.small': 'Small',
  'settings.uiScale.normal': 'Normal',
  'settings.uiScale.large': 'Large',
  'settings.uiScale.xlarge': 'Extra large',
  'settings.export': 'Export save',
  'settings.import': 'Import save',
  'settings.exported': 'Save copied — keep it somewhere cozy.',
  'settings.imported': 'Island restored!',
  'settings.importFailed': 'That didn’t look like a Poplands save.',

  // item names (stable keys per catalog ids)
  'item.nature.tree': 'Little Tree',
  'item.nature.bush': 'Round Bush',
  'item.nature.flower.purple': 'Bellbloom',
  'item.nature.flower.red': 'Poppykiss',
  'item.nature.flower.yellow': 'Sunnybud',
  'item.nature.grass': 'Grass Tuft',
  'item.nature.mushroom': 'Toadstool',
  'item.nature.pebble': 'Pebble Patch',
  'item.nature.rock': 'Small Rock',
  'item.nature.clover': 'Leafy Clover',
  'item.nature.fern': 'Fern Fan',
  'item.nature.pine': 'Tall Pine',
  'item.decor.fence': 'Wooden Fence',
  'item.decor.fence.gate': 'Picket Gate',
  'item.decor.bench': 'Garden Bench',
  'item.decor.pot': 'Clay Pot',
  'item.decor.stump': 'Log Seat',
  'item.decor.sign': 'Signpost',
  'item.decor.lantern': 'Lantern',
  'item.decor.hedge': 'Hedge',
  'item.ground.path.dirt': 'Dirt Path',
  'item.ground.path.stone': 'Stepping Stones',
  'item.income.stall': 'Flower Stall',
  'item.home.hut': 'Cozy Hut',
  'item.home.house': 'Wildwood House',
  // Tier 3-6
  'item.income.pumpkin-patch': 'Pumpkin Patch',
  'item.income.wheat-field': 'Wheat Field',
  'item.nature.apple-tree': 'Apple Tree',
  'item.nature.berry-bush': 'Berry Bush',
  'item.nature.corn': 'Corn Stalk',
  'item.decor.hay-bale': 'Hay Bale',
  'item.decor.campfire': 'Campfire',
  'item.home.farmhouse': 'Farmhouse',
  'item.decor.cart': 'Wooden Cart',
  'item.decor.log-pile': 'Log Pile',
  'item.nature.carrot': 'Carrot Row',
  'item.income.market-stall': 'Market Stall',
  'item.income.bakery': 'Bakery',
  'item.home.village-house': 'Village House',
  'item.decor.fountain': 'Fountain',
  'item.decor.lightpost': 'Street Lamp',
  'item.decor.banner': 'Town Banner',
  'item.income.watermill': 'Watermill',
  'item.decor.statue': 'Stone Statue',
  'item.decor.stone-bridge': 'Stone Bridge',
  // Tier 7–8 "Riverside"
  'item.income.fish-market': 'Fish Market',
  'item.ground.river': 'River Tile',
  'item.decor.wooden-bridge': 'Wooden Bridge',
  'item.nature.lily-pad': 'Lily Pads',
  'item.nature.reeds': 'Reed Cluster',
  'item.income.cider-mill': 'Cider Mill',
  'item.home.fishing-hut': 'Fishing Hut',
  'item.decor.canoe': 'Canoe',
  // Tier 9–10 "Harbor"
  'item.income.harbor-market': 'Harbor Market',
  'item.decor.dock': 'Dock',
  'item.nature.palm': 'Palm Tree',
  'item.nature.beach-rock': 'Beach Rocks',
  'item.decor.crate': 'Crate Stack',
  'item.decor.barrel': 'Barrel',
  'item.income.lighthouse': 'Lighthouse',
  'item.decor.moored-sloop': 'Moored Sloop',
  'item.decor.pennant': 'Pennant Flag',
  // Tiers 11-14 (v0.6)
  'item.nature.palm-leaning': 'Leaning Palm',
  'item.nature.coconut-palm': 'Coconut Palm',
  'item.nature.beach-grass': 'Beach Grass',
  'item.nature.sea-boulder': 'Coastal Boulders',
  'item.nature.tropical-brush': 'Tropical Brush',
  'item.decor.rowboat': 'Rowboat',
  'item.decor.jetty': 'Jetty',
  'item.decor.raft': 'Plank Raft',
  'item.decor.treasure-chest': 'Treasure Chest',
  'item.decor.bottle-crate': 'Bottle Crate',
  'item.decor.cannon': 'Harbor Cannon',
  'item.decor.harbor-flag': 'Harbor Flag',
  'item.decor.oar': 'Leaning Oar',
  'item.decor.shipwreck': 'Beached Shipwreck',
  'item.income.boathouse': 'Boathouse',
  'item.nature.dead-pine': 'Dead Pine',
  'item.nature.dead-trunk': 'Bare Trunk',
  'item.decor.gravestone-round': 'Round Headstone',
  'item.decor.gravestone-cross': 'Cross Headstone',
  'item.decor.gravestone-decorative': 'Ornate Grave',
  'item.decor.gravestone-broken': 'Broken Headstone',
  'item.decor.obelisk': 'Memorial Obelisk',
  'item.decor.wooden-cross': 'Wooden Cross',
  'item.decor.coffin': 'Coffin',
  'item.decor.jack-o-lantern': 'Jack-o\'-Lantern',
  'item.decor.candles': 'Grave Candles',
  'item.decor.brazier': 'Fire Brazier',
  'item.decor.spirit-lantern': 'Spirit Lantern',
  'item.decor.iron-fence': 'Iron Fence',
  'item.decor.iron-gate': 'Iron Gate',
  'item.income.mausoleum': 'Grand Mausoleum',
  'item.home.keepers-crypt': 'Keeper\'s Crypt',
  'item.nature.snow-pine': 'Snow Pine',
  'item.nature.blue-spruce': 'Blue Spruce',
  'item.nature.little-pine': 'Little Pine',
  'item.nature.ice-rock': 'Ice Rock',
  'item.nature.snow-boulder': 'Snow Boulder',
  'item.decor.firewood': 'Firewood Stack',
  'item.decor.snow-log': 'Snowy Log',
  'item.decor.warming-fire': 'Warming Fire',
  'item.decor.frost-stump': 'Frosted Stump',
  'item.decor.camp-tent': 'Camp Tent',
  'item.ground.frozen-pond': 'Frozen Pond',
  'item.home.log-cabin': 'Log Cabin',
  'item.home.alpine-chalet': 'Alpine Chalet',
  'item.income.warm-lodge': 'Warm Lodge',
  'item.income.cocoa-stall': 'Cocoa Stall',
  'item.income.town-hall': 'Town Hall',
  'item.income.grand-market': 'Grand Market',
  'item.income.grain-mill': 'Grain Mill',
  'item.income.guildhall': 'Merchant Guildhall',
  'item.income.mine': 'Stone Quarry Mine',
  'item.home.manor': 'Manor Estate',
  'item.home.townhouse': 'Grand Townhouse',
  'item.decor.castle': 'Castle Keep',
  'item.decor.temple': 'Grand Temple',
  'item.decor.grand-fountain': 'Grand Fountain',
  'item.decor.monument': 'Founders\' Monument',
  'item.decor.clock-tower': 'Clock Tower',
  'item.decor.market-square': 'Market Square Stalls',
  'item.decor.town-gate': 'Town Gate',
  'item.decor.grand-banner': 'Grand Banner',
} as const;

export type StringKey = keyof typeof en;

const tables: Record<string, Partial<Record<StringKey, string>>> = { en };
let locale = 'en';

export function setLocale(next: string): void {
  if (tables[next]) locale = next;
}

export function t(key: StringKey): string {
  const table = tables[locale];
  const value = table?.[key] ?? en[key];
  if (value === undefined) {
    console.warn(`[strings] missing key: ${key}`);
    return key;
  }
  return value;
}

/** Exposed for tests (completeness checks) and future locale tables. */
export const stringTable = en;
